### ISSUE TITLE
unsafe javascript / errors

### ISSUE THREAD

**Issue by mchambaud** [rdio/jsapi-examples#3]
Unsafe JavaScript attempt to access frame with URL http://localhost/rdio2/ from frame with URL http://rdio.com/api/iframe/?xdm_e=http%3A%2F%2Flocalhost&xdm_c=default5966&xdm_p=1. Domains, protocols and ports must match.

I get the same message on the demo site.

When running on my local web server (or hosted) I get an alert saying invalid redirect http://localhost/rdio2/helper.html?client_id=..........

Any idea what is causing this?!

**Comment by iangilman** [comment]
The "unsafe JavaScript" message is coming from the easyXDM library we're using for iframe communication; it's on my list to sort that out, but it shouldn't cause any problems for you in the meantime.

The "invalid redirect" message is because you need to add your localhost address as an additional redirect URI for your app (on the Rdio developer site).

**Comment by iangilman** [comment]
Turns out the "unsafe JavaScript" error is actually from swfobject.js: http://code.google.com/p/swfobject/wiki/faq#22._Why_does_Firefox_report_Permission_denied_to_call_method_Loc

We're now using a different method that doesn't generate the error.
